// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfvcIbq2a2CWNDYm6LUZwc22d9pb1YKKc',
    appId: '1:14440217307:web:3c6b3f5d7829e11a3e6afe',
    messagingSenderId: '14440217307',
    projectId: 'itus-ansurance',
    authDomain: 'itus-ansurance.firebaseapp.com',
    storageBucket: 'itus-ansurance.appspot.com',
    measurementId: 'G-X01MST6BRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzgDjwtKJfEoE9HLTx797CAR57nLuATuc',
    appId: '1:14440217307:android:ef9256ec882fc0dd3e6afe',
    messagingSenderId: '14440217307',
    projectId: 'itus-ansurance',
    storageBucket: 'itus-ansurance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYkL3wrY8hJJ0tr8J9gQqpL0VR1DrDShE',
    appId: '1:14440217307:ios:34f7e3403f2b1c803e6afe',
    messagingSenderId: '14440217307',
    projectId: 'itus-ansurance',
    storageBucket: 'itus-ansurance.appspot.com',
    iosBundleId: 'com.example.pfeProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYkL3wrY8hJJ0tr8J9gQqpL0VR1DrDShE',
    appId: '1:14440217307:ios:6e02fcc71c267b6a3e6afe',
    messagingSenderId: '14440217307',
    projectId: 'itus-ansurance',
    storageBucket: 'itus-ansurance.appspot.com',
    iosBundleId: 'com.example.pfeProjet.RunnerTests',
  );
}
